name: flutter_template_maker
description: >
  A tool for automatically creating Flutter templates 
  from existing Flutter projects.
version: 0.1.0
repository: https://github.com/filiph/flutter_template_maker

environment:
  sdk: ^3.1.3

dependencies:
  args: ^2.4.2
  glob: ^2.1.2
  path: ^1.8.3
  yaml: ^3.1.2

dev_dependencies:
  lints: ^2.0.0
